opt_out_usage
default_platform(:ios)

platform :ios do
  desc "Sets up signing"
  lane :sign_and_build do

  build_app(
    scheme: ENV["APP_SCHEME"],
    skip_codesigning: true,
    skip_archive: true,
    skip_package_ipa: true
  )
  end
end


